modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GPL-3.0"

[[mods]]
modId = "quest_items"
version = "${version}"
displayName = "Quest Items"
authors = "Daedelus"
description = '''
Miscellaneous items of various themes, for quest objectives
'''
logoFile = "icon.png"

[[dependencies.quest_items]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quest_items]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "quest_items.mixins.json"
